#!/bin/bash -e
#
# Watch for changes to files, triggering a build when changes are noticed.
#

RED='\033[1;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

build --no-pdf --no-compress
echo -e "${YELLOW}Initial build completed.${NC}"

build=1

if git ls-files --error-unmatch 'index.??.adoc' > /dev/null; then
	PRIMARY_LANGUAGE=$(git ls-files 'index.??.adoc' | cut -d. -f 2)
else
	PRIMARY_LANGUAGE=en
fi

while true; do
    echo -e "${YELLOW}Watching for changes.  Press ^C to stop.${NC}"
    inotifywait --quiet --event modify *.en.adoc | \
        while read src event; do
            build=$(( $build + 1 ))
            ts=$(date +%H:%M:%S)
            echo -e "${YELLOW}[Build $build at $ts] $src changed${NC}"
            build --no-pdf --no-compress
            echo -e "${YELLOW}[Build $build at $ts] Completed (caused by change to $src)${NC}"
            echo
        done
done
