= GBIF Asciidoctor Toolkit
:source-highlighter: coderay

== The toolkit

This is a Docker container derived from https://github.com/asciidoctor/docker-asciidoctor[docker-asciidoctor], but with the addition of:

* GBIF templates and styling
* GBIF document build script

The Asciidoctor Docker container provides:

* Asciidoctor 2.0.6
* Aciidoctor Diagram with Graphviz integration (supports plantuml and graphiz diagrams)
* Asciidoctor PDF (alpha)
* Asciidoctor EPUB3 (alpha)
* Asciidoctor Mathematical
* AsciiMath
* Source highlighting using CodeRay or Pygments
* Asciidoctor Confluence

== How to use it

From the top-level directory containing the GBIF document, run:

[source,bash]
----
docker run --rm -it -v $PWD:/documents/ mb.gbif.org:5000/gbif-asciidoctor-toolkit
----

Your documents will be processed, and output in the same directory.

== How to contribute / do it yourself ?

_(Section not updated.)_

=== Requirements

You need the following tools:

* A bash compliant command line
* link:http://man7.org/linux/man-pages/man1/make.1.html[GNU make]
* link:https://github.com/sstephenson/bats[bats] installed and in your bash PATH
* Docker installed and in your path

=== How to build and test ?

* "bats" is used as a test suite runner. Since the ability to build is one way of testing, it is included.

* You just have to run the bats test suite, from the repository root:
+
[source,bash]
----
make test
----

==== Include test in your build pipeline or test manually

You can use bats directly to test the image, optional you can use a custome image name:

[source,bash]
----
# If you want to use a custom name for the image, OPTIONAL
export DOCKER_IMAGE_NAME_TO_TEST=your-image-name
bats tests/*.bats
----
