= GBIF Asciidoctor Toolkit
:source-highlighter: coderay

== The toolkit

This is a Docker container derived from https://github.com/asciidoctor/docker-asciidoctor[docker-asciidoctor], but with the addition of:

* GBIF templates and styling
* GBIF document build script

The Asciidoctor Docker container provides:

* Asciidoctor
* Asciidoctor Diagram with Graphviz integration (supports plantuml and graphiz diagrams)
* Asciidoctor PDF
* Asciidoctor EPUB3
* Asciidoctor Mathematical
* AsciiMath
* Source highlighting using CodeRay or Rouge
* Asciidoctor Confluence

== How to use it

From the top-level directory containing the GBIF document, run:

[source,bash]
----
docker run --rm -it --user $(id -u):$(id -g) -v $PWD:/documents/ gbif/asciidoctor-toolkit
----

Your documents will be processed, and output in the same directory.

To have the HTML document rebuild as changes to the source files are saved, use
[source,bash]
----
docker run --rm -it --user $(id -u):$(id -g) -v $PWD:/documents/ gbif/asciidoctor-toolkit continuous
----

== Component details

There are multiple ways to change Asciidoctor templates, two are used here.  This can help me decide
whether I should only use one method.

=== `gbif-templates`

These templates are copied from https://github.com/asciidoctor/asciidoctor-backends, which are examples
(no longer maintained).

Only the templates that need to be overridden are copied, with some changes to bring them up-to-date
with the HTML converter.

=== `GbifHtmlConverter.rb`

This overrides just particular methods of the Ruby converter.
